### ISSUE TITLE
Provide an API to log in users, and to store and retrieve custom user data.

### ISSUE THREAD

**Issue by eweitnauer** [eweitnauer/gm-play-iub-2017#126]

**Comment by eweitnauer** [comment]
Here is an example how to login, set the user data and get the user data: https://graspablemath.com/auth/auth-demo.html

The relevant code for you is linked to in the README of this repo.

This will only work once we put the game on the graspablemath.com server, so don't be surprised if you can't get the data so far. Just integrate it and pretend that it will work. What you should do is write your own setGameData and getGameData replacement functions that are just using the localStorage and setTimeout to wait for 0.5s before they send any data back. This will simulate how the actual function works later.

The tricky part in this is that you need to make sure it still works when people don't log in. So you need to continue to use the local storage as you are right now. When a user logs in, you want to update the localStorage with the server data. Then each time the player finishes a level, you should update both the local storage and the server.

**Comment by Sameedha** [comment]
We are able to make this work and successfully log in the system. However, since we host our game on a local server, the API was initially giving error for 'Cross Origin Requests' during callback. 
During the implementation part, we tested by disabling 'CORS policy' on our specific browsers.
To make the login feature work on all browsers (with default security settings), we may have to use postMessage() which will allows cross origin requests, but that needs to be implemented on both sides ( GM as well as our team). Please let us know how can we proceed with this or if a better option is available other than postMessage ?

**Comment by eweitnauer** [comment]
We'll have the game run on the graspablemath server later. That should
solve this problem, right?

**Comment by Sameedha** [comment]
Yes. I guess, then problem is solved. 
For demo, we will just disable the CORS policy on our browser.
Thanks.
