### ISSUE TITLE
Tutorial video issue

### ISSUE THREAD

**Issue by shreeharshas** [eweitnauer/gm-play-iub-2017#139]
Sometimes in chrome, the first video does not play. We need to scroll to the next or previous pair and come back to current one to make it active. This needs to be fixed.

**Comment by eweitnauer** [comment]
Whenever this happens to me, the `rect` element on the play-button overlay is sized (0,0). Maybe we can set the width of that rect to (100%, 100%) instead, so it will always have the right size?

We need to test whether `(100%, 100%)` for width and height of an svg rect works in all browsers, though. Alternatively, we could use a div to capture input events.

**Comment by shreeharshas** [comment]
Also adding the note about visibility and display properties discussed earlier today.

**Comment by dgbrokaw** [comment]
Is this the same problem that happened here: https://github.com/eweitnauer/gm-play-iub-2017/issues/87?

The fix we made was this:
```
$(innerDiv.parentElement).on('slid.bs.carousel', function() {
    pair.play_btn.remove();
    pair.play_btn.init();
});
```

Since you say that if you scroll to the next pair, go back, and it works, then I think that means this re-initialization is fixing the problem, but it's being called too late, because it waits for a "slid" event to run. In this case, because it's the first example, there is no "slid" event to reach it.

**Comment by dgbrokaw** [comment]
Is this an issue on the tutorials past level 1? I tried the tutorial on level 1 and it worked. Do you know a more specific time where it fails?

**Comment by dgbrokaw** [comment]
I was playing around in the game for a bit.  I found that in the grades 7-9 section, the tutorial pair that was shown first was actually the second example.  This was the tutorial for level 1.  It was showing the `1/2` example before the `1+2` example.  When I ran these two lines on that tutorial pair
```
pair.play_btn.remove();
pair.play_btn.init();
```
the problem was fixed.

I think this means we can fix the problem either by figuring out why something other than the first example is shown first, or figure out when's a better time to run the fix.

**Comment by dgbrokaw** [comment]
@eweitnauer I looked at the svg play button code, and yes, we do set a specific height/width on the rectangle within the svg.

**Comment by shreeharshas** [comment]
@dgbrokaw : I believe it is related to #165 , please have a look at the attached file [staticExprBug.zip](https://github.com/eweitnauer/gm-play-iub-2017/files/939297/staticExprBug.zip)

Also, we found that using **visibility** instead of "display" property of CSS while integrating the new staticExpressions avoided this issue.

**Comment by eweitnauer** [comment]
So can you try to apply the same to the carousell you use for the tutorials?

If not (because the styling is controlled by bootstrap), try to find a way to only initialize the tutorial pairs *after* they are made visible.

**Comment by shreeharshas** [comment]
Sure, I am looking into it.

**Comment by shreeharshas** [comment]
Root cause found and fixed!

Issue: When the tutorial for 1st level completes, all the tutorial pairs are moved instead of the current one.
This caused the inactive tutorial pairs to be displayed in the subsequent levels. These inactive paris were not clickable.

Fix: Instead of auto scrolling all the tutorials, scrolled only the currently solved tutorial.
