### ISSUE TITLE
Equation overlap issue

### ISSUE THREAD

**Issue by shreeharshas** [eweitnauer/gm-play-iub-2017#157]
Regarding issue #138 where equations overlap on one another.

We found that the issue is due to the newer version of the GM API. The last working GM version was 0.14.0 which did not cause the overlap error.

The attached file "eqOverlapBug.zip" contains two files "eqOverlapBug.html" and "GM_overlap.pptx".

To reproduce this error, please use the html file and follow the steps:

1. Open the attached file in browser and click on the "Start timer" button
2. Drag and hold the + sign outside the equation until the timer hits zero. (Please refer to "GM_overlap.pptx" for screenshots).
3. Once the timer hits 0, release the sign.
4. The equation overlaps on a newly created equation.
5. Update GM version to _0.14.0_ and repeat above steps - this will not cause the error.

We verified with versions from 0.15.0 to 2.0.0 and found the issue to be present, request fix.

[eqOverlapBug.zip](https://github.com/eweitnauer/gm-play-iub-2017/files/927171/eqOverlapBug.zip)

**Comment by eweitnauer** [comment]
I think all we need to do is abort any interaction that might be going on in a view of a derivation when it is removed.

I'm a little curious why a removed DL currently shows up again when we don't abort an ongoing interaction, but don't spend too much time on finding out. Just take a short look :)

**Comment by eweitnauer** [comment]
@shreeharshas Actually, you should not be running into this issue. You should use the "changed", not the "change" event to check whether the player solved an egg. When they solved it, you should immediately set the derivation to be non-interactive. This way, it is impossible for the user to drag a term while you remove the derivation.

**Comment by LaxmiBhavaniM** [comment]
@eweitnauer . This issue occurs when a term is just dragged a bit from its original position, without changing its position relative to other terms in the expression. In this case, neither "el_changed" nor "el_change" events occur. In the sample code that we provided you, we haven't used "el_changed" or "el_change".

In the game, this happens when the player is trying to match the last rock expression, but the rock hits the egg and bursts. The game switches to "egg solving mode" while the player's interaction with the canvas is still on and he is still trying to solve by holding a term in the rock expression.

**Comment by eweitnauer** [comment]
That makes sense, thank you for the clarification!
David is working on a solution!

**Comment by eweitnauer** [comment]
This should be solved in version 2.0.1. Please test and close the issue if it works now!

**Comment by LaxmiBhavaniM** [comment]
Works fine without any issues in v2.0.1. Thanks.
