### ISSUE TITLE
Give them the painted background image

### ISSUE THREAD

**Issue by eweitnauer** [eweitnauer/gm-play-iub-2017#167]

**Comment by eweitnauer** [comment]
Here is the new background image. Please use it.
![dino-bg-lq](https://cloud.githubusercontent.com/assets/53043/25285634/ef178cde-2688-11e7-9e7b-6e0e9ff3a4de.jpg)

Don't use an extra area for the canvas in the bottom. Just place the canvas on top of the bottom of the picture.

**Comment by eweitnauer** [comment]
I put some new graphics for the eggs up in the next days. Should be easy to replace!

**Comment by eweitnauer** [comment]
I pushed the new graphics to a top-level assets folder

**Comment by eweitnauer** [comment]
The only difference for the dino-mom is that it now has a half-transparent shadow. Can you apply this to the dino-mom animations you did?

**Comment by Sameedha** [comment]
Hi Erik,
Thanks for the new graphics. We will try to apply the animations to new images.

**Comment by Sameedha** [comment]
Hi Erik,
We added the new sprites with shadow in demo_12. However, since the new background is water color based, it does not mix well with the current graphics (other game objects). Attached is the image with new background. Please let us know if this seems okay.
<img width="806" alt="screen shot 2017-04-25 at 12 05 41 am" src="https://cloud.githubusercontent.com/assets/22250973/25368523/0c4661da-294b-11e7-9702-12a378e8a061.png">

**Comment by shreeharshas** [comment]
Avoided the use of the extra area for the canvas in the bottom and placed the canvas accordingly by Pull request #175

**Comment by eweitnauer** [comment]
@Sameedha 
You obviously need to scale the images appropriately to make them work together!

Please use the aspect-ratio of the background image instead of your current aspect ratio. Currently, your ratio is 4:3, which does not match most display ratios. This probably means that you have to adjust where on the screen you show the graphical elements of the game.

**Comment by Sameedha** [comment]
Thanks for pointing about aspect ratio. We were missing that with our old background as well. 
I have fixed this locally and attached a screenshot of the same. Now, this background looks fine since all of the eggs and dino seem to stand on a hill and their shadows are also visible.
We can close this issue once you approve. Thanks.

PS - The flaming thing in the image is the fire produced due to rock burst.

<img width="804" alt="screen shot 2017-04-25 at 9 00 27 pm" src="https://cloud.githubusercontent.com/assets/22250973/25413742/9a93e50c-29fa-11e7-975c-ae817d469344.png">

**Comment by Sameedha** [comment]
After today's demo in team meeting, we have finalized this UI. Hence, closing this issue.
